services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    command: pnpm run dev --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8080
    working_dir: /app